server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true